'use strict';
// Builds the static website for GitHub Pages (or any static host) from public/.
//
//   node scripts/build-site.js --url https://xxxx.supabase.co --key <publishable-or-anon-key> --out ../genesis-hackathon-site
//
// The output folder only ever contains files this script created: it refuses to
// clear a non-empty folder that lacks the .genesis-site marker.
const fs = require('node:fs');
const path = require('node:path');

const args = Object.fromEntries(
  process.argv.slice(2).reduce((acc, a, i, all) => (a.startsWith('--') ? [...acc, [a.slice(2), all[i + 1]]] : acc), [])
);
// Defaults come from site.config.json (publishable key only — safe to commit).
let saved = {};
try {
  saved = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'site.config.json'), 'utf8'));
} catch {
  /* no saved config */
}
const url = (args.url || process.env.SUPABASE_URL || saved.supabaseUrl || '').replace(/\/+$/, '');
const key = args.key || process.env.SUPABASE_KEY || saved.supabaseKey || '';
const out = path.resolve(path.join(__dirname, '..'), args.out || saved.out || 'site-build');
const src = path.join(__dirname, '..', 'public');

if (!/^https?:\/\/[^\s'"]+$/.test(url) || !key || /['"\s]/.test(key)) {
  console.error('Usage: node scripts/build-site.js --url https://xxxx.supabase.co --key <publishable-key> [--out folder]');
  process.exit(1);
}
if (/service_role|sb_secret_/.test(key) || (key.startsWith('eyJ') && JSON.parse(Buffer.from(key.split('.')[1] || '', 'base64url').toString() || '{}').role === 'service_role')) {
  console.error('That is a SECRET (service_role) key. Use the publishable / anon key instead. Never put the secret key in a website.');
  process.exit(1);
}

const MARKER = '.genesis-site';
fs.mkdirSync(out, { recursive: true });
const existing = fs.readdirSync(out).filter((f) => f !== '.git');
if (existing.length && !existing.includes(MARKER)) {
  console.error(`Refusing to overwrite ${out}: it has files not created by this script.`);
  process.exit(1);
}
for (const f of existing) fs.rmSync(path.join(out, f), { recursive: true, force: true });

// Plain recursive copy (fs.cpSync crashes on some Windows paths in Node 24).
function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const a = path.join(from, entry.name);
    const b = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(a, b);
    else if (entry.isFile()) fs.copyFileSync(a, b);
  }
}
copyDir(src, out);

fs.writeFileSync(
  path.join(out, 'js', 'config.js'),
  `// Generated by scripts/build-site.js. The publishable key is meant to be public.
export const CONFIG = {
  supabaseUrl: ${JSON.stringify(url)},
  supabaseKey: ${JSON.stringify(key)},
};
`
);

const wss = url.replace(/^http/, 'ws');
const csp = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self'",
  `connect-src 'self' ${url} ${wss}`,
  "base-uri 'self'",
  "form-action 'self'",
].join('; ');
for (const f of fs.readdirSync(out).filter((x) => x.endsWith('.html'))) {
  const p = path.join(out, f);
  const html = fs.readFileSync(p, 'utf8').replace(
    '<meta charset="utf-8">',
    `<meta charset="utf-8">\n  <meta http-equiv="Content-Security-Policy" content="${csp}">\n  <meta name="referrer" content="same-origin">`
  );
  fs.writeFileSync(p, html);
}

fs.writeFileSync(path.join(out, '.nojekyll'), '');
fs.writeFileSync(path.join(out, MARKER), 'Built by Genesis_Hackathon/scripts/build-site.js. Do not edit by hand; rebuild instead.\n');
fs.writeFileSync(
  path.join(out, 'README.md'),
  `# Genesis Hackathon — website

This repository holds only the built website (HTML, CSS, JavaScript, images).
It is published with GitHub Pages. The data lives in Supabase; no passwords,
scores or other event data are stored here.

Do not edit these files directly. Change the source project and rebuild with
\`node scripts/build-site.js\`.
`
);
console.log(`Site built in ${out}`);
